# Generated by Django 4.2.7 on 2025-09-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='app1.room'),
        ),
    ]
