# Generated by Django 4.2.7 on 2025-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_gallery_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
