# Generated by Django 4.2.7 on 2025-09-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.rooms'),
        ),
    ]
