# Generated by Django 4.2.7 on 2025-09-15 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_a_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gallery'),
        ),
    ]
