# Generated by Django 4.2.7 on 2025-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_booking_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
