# Generated by Django 4.2.7 on 2025-09-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_billing_email_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.booking'),
        ),
    ]
